# Generated by Django 4.1.6 on 2023-02-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_flag_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(to='api.category'),
        ),
    ]
