# Generated by Django 4.0.6 on 2023-03-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_photo_bitmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='bitmap',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('user', 'photo')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'photo')},
        ),
    ]
