# Generated by Django 4.0.6 on 2023-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_location_google_id_alter_photo_bitmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
