name: PR Review Requested

on:
  pull_request:
    types: [review_requested]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
            args: https://github.com/${{ github.event.repository.organization }}/${{ github.event.repository.name }}/pull/${{ github.event.number }}
