name: PR Review Requested

on:
  pull_request:
    types: [review_requested]
  workflow_dispatch:

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Agam
      - if: contains(github.event.pull_request.requested_reviewers.*.login, 'Agam642')
        run: echo "AGAM=' <@193137013686272001>'" >> $GITHUB_ENV
      # Daniel
      - if: contains(github.event.pull_request.requested_reviewers.*.login, 'danielkim10')
        run: echo "DANIEL=' <@173275763343228928>'" >> $GITHUB_ENV
      # Gautham
      - if: contains(github.event.pull_request.requested_reviewers.*.login, 'gerathas')
        run: echo "GAUTHAM=' <@366918750181654529>'" >> $GITHUB_ENV
      # Kevin
      - if: contains(github.event.pull_request.requested_reviewers.*.login, 'kcchik')
        run: echo "KEVIN=' <@173275228858744832>'" >> $GITHUB_ENV
      # Raymond
      - if: contains(github.event.pull_request.requested_reviewers.*.login, 'Raymond-Xia')
        run: echo "RAYMOND=' <@229057224364785667>'" >> $GITHUB_ENV
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_URL: https://github.com/snaplapse/${{ github.event.repository.name }}/pull/${{ github.event.number }}
        uses: Ilshidur/action-discord@master
        with:
            args: ${{ env.PR_URL }}${{ env.AGAM }}${{ env.DANIEL }}${{ env.GAUTHAM }}${{ env.KEVIN }}${{ env.RAYMOND }}
