name: PR Review Requested

on:
  pull_request:
    types: [review_requested]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_URL: https://github.com/snaplapse/${{ github.event.repository.name }}/pull/${{ github.event.number }}
          TAG: poo#2495
        uses: Ilshidur/action-discord@master
        with:
            args: ${{ env.PR_URL }} @${{ env.TAG }}
